# Generated by Django 2.0 on 2017-12-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '未知')], default=1, verbose_name='性别'),
        ),
    ]
